library("spdep")
library("rstan")
library("parallel")
library("loo")
library("bridgesampling")
library("splines")
library("stringr")
library("INLA")
library("stringr")

# Optional
library("ggplot2")
library("viridis")
library("gridExtra")

source("models.R")
source("utils.R")
source("data_stan.R")
source("fit_stan.R")
source("distributions.R")
source("result_processing.R")
